version: '3.7'

volumes:
  database_volume:

services:
  database:
    env_file:
      - infrastructure/database/.env
    image: mariadb:10.5
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - database_volume:/var/lib/mysql
